server:
  port: 3344
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: https://github.com/pomo16/microservicecloud-config.git
          
